### ISSUE TITLE
totalResults doesn't get the right value

### ISSUE THREAD

**Issue by janlonden** [10up/elasticpress-react#12]
**Describe the bug**
`SearchField` and `LoadMore` uses `response.hits.total.value`, which doesn't exist on the response object, to set `totalResults`. `response.hits.total` does contain the total number of results.

**Environment information**
 - Plugins and version: ElasticPress 3.5.1, @10up/elasticpress-react 1.2.0

**Comment by nicholasio** [comment]
Thanks for the bug report!

I believe this bug is fixed in 2.0.0-rc.5

Can you try with that version?

**Comment by janlonden** [comment]
The bug is not present in `2.0.0-rc.5`. Thank you
