### ISSUE TITLE
What values does node and indexName take ?

### ISSUE THREAD

**Issue by vishalkhialani** [10up/elasticpress-react#16]
**Describe your question**

Hi,
As per the code boilerplate we need to give
`<ElasticPressProvider
		node="http://elasticpress.test/__elasticsearch"
		indexName="elasticpresstest-post-1"
	>
		{/* ElasticPress Components */}
	</ElasticPressProvider>`

What value we need to take from elastic press dashboard for node and index name?

see attached image for ref - [https://nimb.ws/onLpGx](url)

Thank you,Vishal

**Comment by nicholasio** [comment]
Hey, @vishalkhialani you need to extract the node host and the index name from the EP.io endpoint.

They would look something like this:

`https://[account-name].clients.hosted-elasticpress.io` and the indexName `[account-name]--[indexName]`

**Comment by vishalkhialani** [comment]
Hi @nicholasio ,
Thank you. We figured this out but we are facing other issues.
https://github.com/10up/elasticpress-react/issues/18

Thank you,
Vishal

**Comment by kingkero** [comment]
@nicholasio So you have to expose the Elastic instance in the frontend with this, right? What is the advantage of this package over other ElasticSearch React libraries?

Is it possible to "hide" Elastic behind WP? Read: Make the React app talk to the WP instance, which then talks to the Elastic instance.
